# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171113_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile'),
        ),
    ]
