# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 04:20
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171113_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking_account',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=11),
        ),
        migrations.AlterField(
            model_name='saving_account',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=11),
        ),
    ]
