# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logexternal',
            name='account_1',
        ),
        migrations.RemoveField(
            model_name='logexternal',
            name='account_2',
        ),
    ]
