# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('log', '0002_auto_20171111_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='logexternal',
            name='account_1',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='external_account_1', to='account.Checking_Account'),
            preserve_default=False,
        ),
    ]
