# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('log', '0004_auto_20171111_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logexternal',
            name='account_1',
        ),
        migrations.AddField(
            model_name='logexternal',
            name='account_1',
            field=models.ManyToManyField(related_name='external_account_1', to='account.Checking_Account'),
        ),
    ]
