# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('log', '0005_auto_20171111_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='logexternal',
            name='account_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_account_2', to='account.Checking_Account'),
        ),
        migrations.RemoveField(
            model_name='logexternal',
            name='account_1',
        ),
        migrations.AddField(
            model_name='logexternal',
            name='account_1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='external_account_1', to='account.Checking_Account'),
            preserve_default=False,
        ),
    ]
