# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20171111_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginternal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
