# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
